### PR TITLE
WIP SSE2 code

### PR DESCRIPTION
**Pull request by sf-x**
As per #124 . Putting out the draft so that I don't forget about it. No vectorization of anything but affine_transform, and no MMX code. (Although that could wait.)
Also changes `config-sanity' target to print CFLAGS instead of CXXFLAGS

### CODE REVIEW

**Comment by syzygy1** [comment]
I've now added the SSE2 code from Stockfish so we can compare.

I suppose you don't really need `&& !defined(NNUE_NOINT8)` as long as the Makefile does the right thing?

**Comment by sf-x** [comment]
> I suppose you don't really need `&& !defined(NNUE_NOINT8)` as long as the Makefile does the right thing?

If the Makefile is correct, _some_ of those can be removed (those which are next to USE_SSSE3 and above), but not all (the feature transformer can work with SSE2 only, for example). Or the mainline code will need to be removed.

**Comment by sf-x** [comment]
Merged. Now there's two versions of SSE2 code, switched by `nnue_noint8` Make variable .

**Comment by sf-x** [comment]
Thinking about it, unpacking just the weights and not the intermediate results might be better on some CPUs. Maybe I'll try.

**Comment by syzygy1** [comment]
I can confirm a nice speed up.

**Pull request merged**
